/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package userdb;

import java.util.List;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        Database<UserEntry> database = new Database<UserEntry>();
        UserEntry entry1 = new UserEntry("1", new User("Jisu", 31));
        UserEntry entry2 = new UserEntry("2", new User("Jisu2", 31));
        UserEntry entry3 = new UserEntry("3", new User("Jisu3", 31));
        
        database.put(entry1);
        database.put(entry2);
        database.put(entry3);

        List<UserEntry> userEntries = database.getAll();
        for(UserEntry entry : userEntries){
            System.out.println(entry);
        }
    }
}
